name: Sync IP File

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0点执行（北京时间 8点）
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 当前仓库
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 1

      - name: 创建 ip 文件夹（不存在则创建）
        run: mkdir -p ip

      - name: 下载文件到 ip/ 目录
        run: |
          curl -L \
            https://raw.githubusercontent.com/adminouyang/TV-yjc/main/IP_Scan/ip \
            -o ip/ip

      - name: 提交并推送
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: main  # 你的分支，一般是 main 或 master
          commit_message: "Auto sync ip file from remote"
          allow_empty_commit: false
